src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 150)]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $is_verified = false;

    #[ORM\Column]
    private ?bool $agree_terms = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function isVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setVerified(bool $is_verified): static
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function isAgreeTerms(): ?bool
    {
        return $this->agree_terms;
    }

    public function setAgreeTerms(bool $agree_terms): static
    {
        $this->agree_terms = $agree_terms;

        return $this;
    }
}

src/Controller/MyspaceController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class MyspaceController extends AbstractController
{
    #[Route('/profile/myspace', name: 'app_myspace')]
    public function index(
    ): Response
    {
        $user = $this->getUser();
        return $this->render('myspace/index.html.twig', [
            'user' => $user
        ]);
    }
}

templates/myspace/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MyspaceController!{% endblock %}

{% block body %}
    <table class="table">
        <thead>
            <tr>
                <th colspan="2">Vos informations :</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Votre pseudo : </th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Votre email : </th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Vérifié :</th>
                {% if user.isVerified %}
                <td>vérifié</td>
                {% else %}
                <td>non vérifié</td>
                {% endif %}
            </tr>
            <tr>
                <th>Conditions acceptées :</th>
                {% if user.agreeTerms %}
                <td>Conditions acceptées</td>
                {% else %}
                <td>Conditions refusées</td>
                {% endif %}
            </tr>
        </tbody>
    </table>
{% endblock %}